// LOCKED curated order. Public/unprotected sources only; HD-first.
const channels = [
  { rank:1,id:'tv3',name:'TV3',group:'General',provider:'Media Prima',epg:'103',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/103_300.png',officialPage:'https://www.tonton.com.my/',source:{url:'https://unifi-live05.secureswiftcontent.com/UnifiHD/live03.mpd',quality:'HD'} },
  { rank:2,id:'astro-ria',name:'Astro Ria',group:'General',provider:'Astro',epg:'104',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/104_300.png',officialPage:'https://www.astro.com.my/content/channels/Astro-Ria-193' },
  { rank:3,id:'tv1',name:'TV1',group:'General',provider:'RTM',epg:'101',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/101_300.png',officialPage:'https://rtmklik.rtm.gov.my/',source:{url:'https://rtm1hd.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b1064000.m3u8',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} },
  { rank:4,id:'tv2',name:'TV2',group:'General',provider:'RTM',epg:'102',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/102_300.png',officialPage:'https://rtmklik.rtm.gov.my/',source:{url:'https://rtm5hd.secureswiftcontent.com/Origin1/ngrp:RTM1/chunklist_b1064000.m3u8',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} },
  { rank:5,id:'tv-okey',name:'TV Okey',group:'General',provider:'RTM',epg:'146',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/146_300.png',officialPage:'https://rtmklik.rtm.gov.my/',source:{url:'https://rtm2hd.secureswiftcontent.com/Origin02/ngrp:RTM2/chunklist_b1064000.m3u8',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} },
  { rank:6,id:'8tv',name:'8TV',group:'General',provider:'Media Prima',epg:'148',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/148_300.png',officialPage:'https://www.tonton.com.my/',source:{url:'https://unifi-live05.secureswiftcontent.com/UnifiHD/live08.mpd',quality:'HD'} },
  { rank:7,id:'tv9',name:'TV9',group:'General',provider:'Media Prima',epg:'149',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/149_300.png',officialPage:'https://www.tonton.com.my/',source:{url:'https://unifi-live09.secureswiftcontent.com/UnifiHD/live09.mpd',quality:'HD'} },
  { rank:8,id:'astro-awani',name:'Astro Awani',group:'News',provider:'Astro',epg:'501',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/501_300.png',officialPage:'https://www.astroawani.com/',source:{url:'https://awanitv.akamaized.net/hls/live/2017836/LiveTV1/index.m3u8',quality:'1080p'} },
  { rank:9,id:'bernama-tv',name:'Bernama TV',group:'News',provider:'Bernama',epg:'502',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/502_300.png',officialPage:'https://www.bernama.com/' },
  { rank:10,id:'berita-rtm',name:'Berita RTM',group:'News',provider:'RTM',epg:'505',officialPage:'https://berita.rtm.gov.my/live-streaming/',source:{url:'https://rtm3hd.secureswiftcontent.com/Origin03/ngrp:RTM3/chunklist_b1064000.m3u8',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} },
  { rank:11,id:'tv-alhijrah',name:'TV AlHijrah',group:'General',provider:'TV AlHijrah',epg:'114',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/114_300.png',officialPage:'https://www.tvalhijrah.com/',source:{url:'https://unifi-live05.secureswiftcontent.com/UnifiHD/live07.mpd',quality:'HD'} },
  { rank:12,id:'tvs',name:'TVS',group:'General',provider:'TVS',epg:'122',officialPage:'https://www.tvsarawak.my/',source:{url:'https://live-tvs.tvsarawak.my/live/tvs.m3u8',quality:'HD'} },
  { rank:13,id:'sukan-plus',name:'Sukan+',group:'Sports',provider:'RTM',epg:'806',officialPage:'https://rtmklik.rtm.gov.my/',source:{url:'https://rtm6hd.secureswiftcontent.com/Origin2/ngrp:RTM2/chunklist_b1064000.m3u8',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} },
  { rank:14,id:'didik-tv',name:'DidikTV KPM',group:'Kids',provider:'Media Prima',epg:'147',logo:'https://astrocontent.s3.amazonaws.com/Images/ChannelLogo/Pos/147_300.png',officialPage:'https://didik.tv/',source:{url:'https://unifi-live05.secureswiftcontent.com/UnifiHD/live06.mpd',quality:'HD'} },
  { rank:15,id:'tv6',name:'TV6',group:'General',provider:'RTM',epg:'106',officialPage:'https://rtmklik.rtm.gov.my/',source:{url:'https://rtmlive07tv.secureswiftcontent.com/rtmchannel/07-manifest.mpd',quality:'HD',referer:'https://rtmklik.rtm.gov.my/'} }
].sort((a,b)=>a.rank-b.rank);
module.exports=channels;
