const http=require('node:http');
const https=require('node:https');
const zlib=require('node:zlib');
const channels=require('./channels');
const PORT=Number(process.env.PORT||3000); const BASE=process.env.PUBLIC_URL||`http://localhost:${PORT}`;
const groups=['General','News','Sports','Kids'];
const manifest={id:'my.reeqflames.nuvio.malaysia.live',version:'1.3.0',name:'Malaysia Live TV',description:'HD-first Malaysian live TV with Now/Next guide.',resources:['catalog','meta','stream'],types:['tv'],catalogs:[{type:'tv',id:'malaysia-live',name:'Malaysia Live TV'},...groups.map(g=>({type:'tv',id:`malaysia-${g.toLowerCase()}`,name:g}))],idPrefixes:['mytv:'],behaviorHints:{configurable:false,p2pNotSupported:true}};
const logo=c=>c.logo||`${BASE}/logo/${c.id}.svg`; const sourceFor=c=>c.source;
let epg={at:0,items:new Map()}; const EPG='https://www.open-epg.com/files/malaysia3.xml.gz';
function get(url){return new Promise((ok,no)=>https.get(url,{headers:{'User-Agent':'Mozilla/5.0'}},r=>{const a=[];r.on('data',x=>a.push(x));r.on('end',()=>ok(Buffer.concat(a)));r.on('error',no)}).on('error',no));}
const txt=s=>s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').trim();
const dt=s=>{const m=(s||'').match(/(\d{4})(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)/);return m?new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}+08:00`):null};
async function refreshEPG(){if(Date.now()-epg.at<15*60e3)return;try{const raw=await get(EPG);const xml=zlib.gunzipSync(raw).toString('utf8');const map=new Map();for(const c of channels)map.set(c.id,[]);for(const m of xml.matchAll(/<programme\s+start="([^"]+)"\s+stop="([^"]+)"\s+channel="([^"]+)"[^>]*>([\s\S]*?)<\/programme>/g)){const [_,a,b,id,body]=m;const c=channels.find(x=>String(x.epg)===id);if(!c)continue;const title=(body.match(/<title[^>]*>([\s\S]*?)<\/title>/)||[])[1]||'';map.get(c.id).push({start:dt(a),end:dt(b),title:txt(title)});}epg={at:Date.now(),items:map};}catch(e){console.error('EPG',e.message)}}
function guide(c){const n=new Date(),arr=epg.items.get(c.id)||[];const i=arr.findIndex(x=>x.start<=n&&x.end>n);return {now:i>=0?arr[i]:null,next:i>=0?arr[i+1]||null:null};}
function meta(c){const g=guide(c);return{id:`mytv:${c.id}`,type:'tv',name:c.name,poster:logo(c),posterShape:'square',description:g.now?`NOW: ${g.now.title}${g.next?` • NEXT: ${g.next.title}`:''}`:`${c.provider} • ${c.group} • Live TV`,genres:[c.group,'Malaysia','Live TV'],links:c.officialPage?[{name:'Website',category:'official',url:c.officialPage}]:[]};}
function json(res,status,body,age=60){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':`public,max-age=${age}`});res.end(JSON.stringify(body));}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function svg(res,id){const c=channels.find(x=>x.id===id);if(!c){res.writeHead(404);return res.end()};res.writeHead(200,{'content-type':'image/svg+xml'});res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" rx="90" fill="white"/><text x="256" y="285" text-anchor="middle" font-family="Arial" font-size="78" font-weight="700">${esc(c.name)}</text></svg>`)}
function stream(c,s){const o={name:'Malaysia Live TV',title:`${c.name} • ${s.quality||'HD'}`,url:s.url,behaviorHints:{notWebReady:false}};if(s.referer)o.behaviorHints.proxyHeaders={request:{Referer:s.referer}};return o}
function home(res){const rows=channels.map(c=>{const g=guide(c);return `<article><img src="${logo(c)}"><div><b>${c.rank}. ${esc(c.name)}</b><small>${g.now?`NOW · ${esc(g.now.title)}`:esc(c.provider)}</small>${g.next?`<small>Next · ${esc(g.next.title)}</small>`:''}</div><span>${c.source?(c.source.quality||'HD'):'EPG'}</span></article>`}).join('');res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Malaysia Live TV</title><style>body{margin:0;background:#080b12;color:white;font:15px system-ui}main{max-width:900px;margin:auto;padding:35px 18px}p,small{color:#929daf}.grid{display:grid;gap:9px}article{display:flex;gap:13px;align-items:center;background:#111722;border:1px solid #202938;padding:13px;border-radius:14px}img{width:55px;height:55px;object-fit:contain;background:white;border-radius:10px}small{display:block;margin-top:3px}span{margin-left:auto;color:#63e6a4;font-size:11px;font-weight:800}code{color:#9ee6b8}</style><main><h1>Malaysia Live TV</h1><p>HD-first · Live + Now/Next EPG</p><div class=grid>${rows}</div><p>Install: <code>${BASE}/manifest.json</code></p></main>`)}
const server=http.createServer(async(req,res)=>{await refreshEPG();const u=new URL(req.url,BASE);if(u.pathname==='/')return home(res);if(u.pathname==='/health')return json(res,200,{ok:true,version:manifest.version,channels:channels.length,playable:channels.filter(x=>x.source).length,pending:channels.filter(x=>!x.source).map(x=>x.name),epgUpdated:epg.at?new Date(epg.at).toISOString():null},0);if(u.pathname==='/manifest.json')return json(res,200,manifest,300);let m=u.pathname.match(/^\/logo\/([^/]+)\.svg$/);if(m)return svg(res,decodeURIComponent(m[1]));m=u.pathname.match(/^\/catalog\/tv\/([^/]+)\.json$/);if(m){const id=decodeURIComponent(m[1]);let a=channels;if(id!=='malaysia-live'){const g=id.replace('malaysia-','');a=channels.filter(c=>c.group.toLowerCase()===g)}return json(res,200,{metas:a.map(meta)})}m=u.pathname.match(/^\/meta\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));return c?json(res,200,{meta:meta(c)}):json(res,404,{error:'not found'})}m=u.pathname.match(/^\/stream\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));return c?json(res,200,{streams:c.source?[stream(c,c.source)]:[]}):json(res,404,{error:'not found'})}return json(res,404,{error:'not found'})});
server.listen(PORT,'0.0.0.0',()=>console.log(`Malaysia Live TV ${manifest.version}`));
