const http=require('node:http');
const channels=require('./channels');
const PORT=Number(process.env.PORT||3000);
const BASE=process.env.PUBLIC_URL||`http://localhost:${PORT}`;
const groups=['General','News','Sports','Kids'];
const manifest={id:'my.reeqflames.nuvio.malaysia.live',version:'1.2.0',name:'Malaysia Live TV',description:'Curated HD-first Malaysian live TV for Nuvio.',resources:['catalog','meta','stream'],types:['tv'],catalogs:[{type:'tv',id:'malaysia-live',name:'Malaysia Live TV'},...groups.map(g=>({type:'tv',id:`malaysia-${g.toLowerCase()}`,name:g}))],idPrefixes:['mytv:'],behaviorHints:{configurable:false,p2pNotSupported:true}};
const envKey=c=>`STREAM_${c.id.toUpperCase().replace(/-/g,'_')}`;
const logo=c=>c.logo||`${BASE}/logo/${encodeURIComponent(c.id)}.svg`;
const sourceFor=c=>{const override=process.env[envKey(c)];return override?{url:override,quality:'HD'}:c.source;};
function meta(c){return{id:`mytv:${c.id}`,type:'tv',name:c.name,poster:logo(c),posterShape:'square',description:`${c.provider} • ${c.group} • Malaysia Live TV`,genres:[c.group,'Malaysia','Live TV'],links:c.officialPage?[{name:'Website',category:'official',url:c.officialPage}]:[]};}
function json(res,status,body,maxAge=300){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':`public, max-age=${maxAge}`});res.end(JSON.stringify(body));}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function html(res){const rows=channels.map(c=>{const s=sourceFor(c);return `<article><div class="rank">${c.rank}</div><img src="${logo(c)}"><div><b>${esc(c.name)}</b><small>${esc(c.provider)} · ${esc(c.group)}</small></div><span class="${s?'on':'off'}">${s?(s.quality||'HD'):'PENDING'}</span></article>`}).join('');res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Malaysia Live TV</title><style>*{box-sizing:border-box}body{margin:0;background:#080b12;color:#fff;font:15px system-ui}main{max-width:1000px;margin:auto;padding:40px 20px}h1{font-size:34px;margin:0}.sub{color:#9ba4b5}.tabs{display:flex;gap:9px;margin:26px 0}.tabs b{background:#1a2230;padding:9px 16px;border-radius:99px}.tabs b:first-child{background:#e21b2d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}article{background:#111722;border:1px solid #202938;border-radius:15px;padding:14px;display:flex;align-items:center;gap:12px}.rank{color:#6f7a8d;width:18px;text-align:center}img{width:48px;height:48px;border-radius:11px;background:#fff;object-fit:contain}small{display:block;color:#8f9bad;margin-top:3px}article span{margin-left:auto;font-size:10px;font-weight:800}.on{color:#63e6a4}.off{color:#778196}code{color:#9ee6b8;word-break:break-all}</style><main><h1>Malaysia Live TV</h1><p class="sub">Curated HD-first channel lineup for Nuvio</p><div class="tabs"><b>LIVE</b><b>TV GUIDE</b><b>CHANNELS</b></div><div class="grid">${rows}</div><p class="sub">Install URL: <code>${BASE}/manifest.json</code></p></main>`);}
function svg(res,id){const c=channels.find(x=>x.id===id);if(!c){res.writeHead(404);return res.end();}const initials=c.name.replace(/[^A-Za-z0-9+]/g,'').slice(0,5);res.writeHead(200,{'content-type':'image/svg+xml','cache-control':'public,max-age=86400','access-control-allow-origin':'*'});res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" rx="96" fill="#fff"/><text x="256" y="285" text-anchor="middle" font-family="Arial,sans-serif" font-size="92" font-weight="700" fill="#10131a">${esc(initials)}</text></svg>`);}
function streamObject(c,s){const out={name:'Malaysia Live TV',title:`${c.name} • ${s.quality||'HD'}`,url:s.url,behaviorHints:{notWebReady:false}};if(s.referer)out.behaviorHints.proxyHeaders={request:{Referer:s.referer}};return out;}
const server=http.createServer((req,res)=>{const u=new URL(req.url,BASE);if(u.pathname==='/')return html(res);if(u.pathname==='/health')return json(res,200,{ok:true,version:manifest.version,channels:channels.length,playableCandidates:channels.filter(c=>sourceFor(c)).length,pending:channels.filter(c=>!sourceFor(c)).map(c=>c.name)},0);if(u.pathname==='/manifest.json')return json(res,200,manifest,300);let m=u.pathname.match(/^\/logo\/([^/]+)\.svg$/);if(m)return svg(res,decodeURIComponent(m[1]));m=u.pathname.match(/^\/catalog\/tv\/([^/]+)\.json$/);if(m){const id=decodeURIComponent(m[1]);let list=channels;if(id!=='malaysia-live'){const slug=id.replace(/^malaysia-/,'');list=channels.filter(c=>c.group.toLowerCase()===slug);}return json(res,200,{metas:list.map(meta)});}m=u.pathname.match(/^\/meta\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));return c?json(res,200,{meta:meta(c)}):json(res,404,{error:'Channel not found'});}m=u.pathname.match(/^\/stream\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));if(!c)return json(res,404,{error:'Channel not found'});const s=sourceFor(c);return json(res,200,{streams:s?[streamObject(c,s)]:[]},30);}return json(res,404,{error:'Not found'});});
server.listen(PORT,'0.0.0.0',()=>console.log(`Malaysia Live TV v${manifest.version} on ${PORT}`));
