const http=require('node:http');
const channels=require('./channels');
const {runDiagnostics}=require('./diagnostics');
const PORT=Number(process.env.PORT||3000);
const PUBLIC_BASE=process.env.PUBLIC_URL||'https://nuvio-malaysia-live-tv.onrender.com';
const groups=['General','News','Sports','Kids'];
const manifest={id:'my.reeqflames.nuvio.malaysia.live',version:'1.6.1',name:'Malaysia Live TV',description:'Curated HD-first Malaysian live TV.',resources:['catalog','meta','stream'],types:['tv'],catalogs:[{type:'tv',id:'malaysia-live',name:'Malaysia Live TV'},...groups.map(g=>({type:'tv',id:`malaysia-${g.toLowerCase()}`,name:`Malaysia ${g}`}))],idPrefixes:['mytv:'],behaviorHints:{configurable:false,p2pNotSupported:true}};
const logo=c=>c.logo||`${PUBLIC_BASE}/logo/${encodeURIComponent(c.id)}.svg`;
function meta(c){return{id:`mytv:${c.id}`,type:'tv',name:c.name,poster:logo(c),posterShape:'square',description:`${c.provider} • ${c.group} • Malaysia Live TV`,genres:[c.group,'Malaysia','Live TV']};}
function json(res,status,body,age=60){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'*','cache-control':`public,max-age=${age}`});if(res.req?.method==='HEAD')return res.end();res.end(JSON.stringify(body));}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function svg(res,id){const c=channels.find(x=>x.id===id);if(!c){res.writeHead(404);return res.end();}res.writeHead(200,{'content-type':'image/svg+xml','access-control-allow-origin':'*','cache-control':'public,max-age=86400'});if(res.req?.method==='HEAD')return res.end();res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" rx="90" fill="white"/><text x="256" y="285" text-anchor="middle" font-family="Arial" font-size="68" font-weight="700" fill="#111">${esc(c.name)}</text></svg>`);}
function stream(c){if(!c.source)return null;const s=c.source,o={name:'Malaysia Live TV',title:`${c.name} • ${s.quality||'HD'}`,url:s.url,behaviorHints:{notWebReady:false}};if(s.referer)o.behaviorHints.proxyHeaders={request:{Referer:s.referer}};return o;}
function normalizePath(path){let p=path;try{p=decodeURIComponent(p)}catch{}while(p.startsWith('/manifest.json/'))p=p.slice('/manifest.json'.length);return p||'/';}
function home(res){const rows=channels.map(c=>`<article><img src="${logo(c)}"><b>${c.rank}. ${esc(c.name)}</b><span>${c.source?(c.source.quality||'HD'):'PENDING'}</span></article>`).join('');res.writeHead(200,{'content-type':'text/html; charset=utf-8','access-control-allow-origin':'*'});res.end(`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Malaysia Live TV</title><style>body{margin:0;background:#080b12;color:#fff;font:15px system-ui}main{max-width:850px;margin:auto;padding:35px 18px}.grid{display:grid;gap:9px}article{display:flex;align-items:center;gap:13px;background:#111722;border:1px solid #202938;padding:13px;border-radius:14px}img{width:52px;height:52px;object-fit:contain;background:#fff;border-radius:10px}span{margin-left:auto;color:#63e6a4;font-size:11px;font-weight:800}code{color:#9ee6b8}</style><main><h1>Malaysia Live TV</h1><p>Nuvio-compatible build v1.6.1</p><div class=grid>${rows}</div><p><code>${PUBLIC_BASE}/manifest.json</code></p></main>`);}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,PUBLIC_BASE);const p=normalizePath(u.pathname);res.on('finish',()=>console.log(`${req.method} ${u.pathname}${u.search||''} -> ${p} [${res.statusCode}]`));if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'*'});return res.end();}if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'method not allowed'},0);if(p==='/')return home(res);if(p==='/health')return json(res,200,{ok:true,version:manifest.version,channels:channels.length,playable:channels.filter(c=>c.source).length,pending:channels.filter(c=>!c.source).map(c=>c.name)},0);if(p==='/diag'){return json(res,200,await runDiagnostics(),0)}if(p==='/manifest.json')return json(res,200,manifest,0);let m=p.match(/^\/logo\/([^/]+)\.svg$/);if(m)return svg(res,decodeURIComponent(m[1]));m=p.match(/^\/catalog\/tv\/([^/]+?)(?:\/[^/]+)?\.json$/);if(m){const id=decodeURIComponent(m[1]);const list=id==='malaysia-live'?channels:channels.filter(c=>c.group.toLowerCase()===id.replace(/^malaysia-/,''));return json(res,200,{metas:list.map(meta)},10);}m=p.match(/^\/meta\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));return c?json(res,200,{meta:meta(c)},10):json(res,404,{error:'not found'},0);}m=p.match(/^\/stream\/tv\/mytv:([^/]+)\.json$/);if(m){const c=channels.find(x=>x.id===decodeURIComponent(m[1]));if(!c)return json(res,404,{error:'not found'},0);const s=stream(c);return json(res,200,{streams:s?[s]:[]},5);}return json(res,404,{error:'not found',path:p},0);});
server.listen(PORT,'0.0.0.0',()=>console.log(`Malaysia Live TV ${manifest.version} Nuvio-compatible`));